// <auto-generated />
using DrinkBuddy.DataAccess.DbContexts.Contexts.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrinkBuddy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222082110_Profile3")]
    partial class Profile3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrinkBuddy.Data.FavorisierterDrinkTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProfilTableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfilTableId");

                    b.ToTable("FavorisierterDrinkTable", (string)null);
                });

            modelBuilder.Entity("DrinkBuddy.Data.ProfilTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ProfilTable", (string)null);
                });

            modelBuilder.Entity("DrinkBuddy.Data.FavorisierterDrinkTable", b =>
                {
                    b.HasOne("DrinkBuddy.Data.ProfilTable", "ProfilTable")
                        .WithMany("FavorisierteDrinks")
                        .HasForeignKey("ProfilTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfilTable");
                });

            modelBuilder.Entity("DrinkBuddy.Data.ProfilTable", b =>
                {
                    b.Navigation("FavorisierteDrinks");
                });
#pragma warning restore 612, 618
        }
    }
}
